[package]
name = "funnytaskmanager2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
ratatui = "0.29.0"
rusqlite = {version = "0.32.1", features = ["bundled", "chrono"]}
tui-input = "0.11.0"

